/**
 * Studio demo data. Mirrors the client demo workspace so the two lenses
 * describe the same two projects — that's the whole point of §3b.
 */
import type { Studio } from "./types.ts";

const day = 86_400_000;
const now = Date.now();
const iso = (d: number) => new Date(now + d * day).toISOString();
const dayNextMonth = (n: number) => {
  const d = new Date();
  return new Date(d.getFullYear(), d.getMonth() + 1, n, 12).toISOString();
};

export const demoStudio: Studio = {
  currentPersonId: "p_chike",
  people: [
    { id: "p_chike", name: "Chike", initials: "CA", role: "super_admin" },
    { id: "p_ada", name: "Ada", initials: "AO", role: "lead" },
    { id: "p_femi", name: "Femi", initials: "FB", role: "member" },
  ],

  projects: [
    {
      id: "prj_brand",
      slug: "brand-identity",
      name: "Brand Identity",
      clientName: "Ovis Health",
      typeName: "Brand identity",
      health: "blocked",
      healthNote: "We’re holding until you pick a direction.",
      targetEndOn: dayNextMonth(12),
      leadId: "p_chike",
      lastPublishedAt: iso(-9),
      clientActions: [
        {
          id: "ca_1",
          title: "Pick a direction from the three concepts",
          dueOn: iso(-2),
          createdAt: iso(-9),
        },
      ],
      tasks: [
        {
          id: "t_1",
          projectId: "prj_brand",
          title: "Refine chosen direction",
          responsibleId: "p_chike",
          status: "blocked",
          dueOn: iso(4),
          deliverableId: null,
          stateChangedAt: iso(-9),
          blockers: [
            {
              id: "b_1",
              kind: "client",
              clientActionId: "ca_1",
              note: "Can’t refine until they choose",
              createdAt: iso(-9),
              resolvedAt: null,
            },
          ],
        },
        {
          id: "t_2",
          projectId: "prj_brand",
          title: "Draft brand guidelines outline",
          responsibleId: "p_ada",
          status: "in_progress",
          dueOn: iso(3),
          deliverableId: null,
          stateChangedAt: iso(-2),
          blockers: [],
        },
        {
          id: "t_3",
          projectId: "prj_brand",
          title: "Prepare typography specimen",
          responsibleId: "p_femi",
          status: "blocked",
          dueOn: iso(1),
          deliverableId: null,
          stateChangedAt: iso(-4),
          blockers: [
            {
              id: "b_2",
              kind: "person",
              blockedByPersonId: "p_ada",
              note: "Waiting on the type licence decision",
              createdAt: iso(-4),
              resolvedAt: null,
            },
          ],
        },
      ],
      deliverables: [
        {
          id: "dlv_concepts",
          name: "Three logo directions",
          typeName: "Logo concepts",
          status: "in_review",
          ownerId: "p_chike",
          round: 1,
          roundsIncluded: 2,
          stateChangedAt: iso(-9),
          reviewUrl: "https://www.figma.com/proto/ovis-concepts",
          linkAccessOk: true,
          checklist: null,
        },
        {
          id: "dlv_iconset",
          name: "Icon set",
          typeName: "Icon set",
          status: "draft",
          ownerId: "p_femi",
          round: 1,
          roundsIncluded: 2,
          stateChangedAt: iso(-1),
          reviewUrl: "https://drive.google.com/drive/folders/ovis-icons",
          linkAccessOk: null,
          checklist: {
            deliverableId: "dlv_iconset",
            templateName: "Icon set",
            templateVersion: 2,
            items: [
              {
                id: "ci_1",
                position: 1,
                label: "SVG set exported and optimised",
                guidance: "Outline strokes, strip metadata, 24px artboard.",
                isRequired: true,
                evidenceKind: "link",
                expectedSource: "Drive",
                requiresCountersign: false,
                isFinalDeliverable: true,
                state: "checked",
                checkedById: "p_femi",
                checkedAt: iso(-1),
                countersignedById: null,
                evidenceUrl: "https://drive.google.com/drive/folders/ovis-icons-svg",
                evidenceText: null,
                waivedReason: null,
              },
              {
                id: "ci_2",
                position: 2,
                label: "PNG set @1x/2x/3x",
                guidance: null,
                isRequired: true,
                evidenceKind: "link",
                expectedSource: "Drive",
                requiresCountersign: false,
                isFinalDeliverable: true,
                state: "checked",
                checkedById: "p_femi",
                checkedAt: iso(-1),
                countersignedById: null,
                evidenceUrl: "https://drive.google.com/drive/folders/ovis-icons-png",
                evidenceText: null,
                waivedReason: null,
              },
              {
                id: "ci_3",
                position: 3,
                label: "Consistent grid and stroke weight",
                guidance: "Every icon on the same 24px grid, 1.5px stroke.",
                isRequired: true,
                evidenceKind: "none",
                expectedSource: null,
                requiresCountersign: false,
                isFinalDeliverable: false,
                state: "checked",
                checkedById: "p_femi",
                checkedAt: iso(-1),
                countersignedById: null,
                evidenceUrl: null,
                evidenceText: null,
                waivedReason: null,
              },
              {
                id: "ci_4",
                position: 4,
                label: "Named per convention",
                guidance: "kebab-case, category prefix.",
                isRequired: true,
                evidenceKind: "none",
                expectedSource: null,
                requiresCountersign: false,
                isFinalDeliverable: false,
                state: "open",
                checkedById: null,
                checkedAt: null,
                countersignedById: null,
                evidenceUrl: null,
                evidenceText: null,
                waivedReason: null,
              },
              {
                id: "ci_5",
                position: 5,
                label: "Contrast checked",
                guidance: "Against both surfaces. Self-certification isn’t enough here.",
                isRequired: true,
                evidenceKind: "text",
                expectedSource: null,
                requiresCountersign: true,
                isFinalDeliverable: false,
                state: "checked",
                checkedById: "p_femi",
                checkedAt: iso(-1),
                countersignedById: null,
                evidenceUrl: null,
                evidenceText: "Checked at 4.6:1 minimum on both paper and ink.",
                waivedReason: null,
              },
              {
                id: "ci_6",
                position: 6,
                label: "Source file archived to brand library",
                guidance: null,
                isRequired: true,
                evidenceKind: "link",
                expectedSource: "Figma",
                requiresCountersign: false,
                isFinalDeliverable: false,
                state: "open",
                checkedById: null,
                checkedAt: null,
                countersignedById: null,
                evidenceUrl: null,
                evidenceText: null,
                waivedReason: null,
              },
              {
                id: "ci_7",
                position: 7,
                label: "Client sharing permissions verified",
                guidance: "Nothing publishes with a link they can’t open.",
                isRequired: true,
                evidenceKind: "none",
                expectedSource: null,
                requiresCountersign: false,
                isFinalDeliverable: false,
                state: "open",
                checkedById: null,
                checkedAt: null,
                countersignedById: null,
                evidenceUrl: null,
                evidenceText: null,
                waivedReason: null,
              },
            ],
          },
        },
      ],
    },

    {
      id: "prj_site",
      slug: "website",
      name: "Website",
      clientName: "Ovis Health",
      typeName: "Website",
      health: "on_track",
      healthNote: "Design’s done. We’re building.",
      targetEndOn: dayNextMonth(28),
      leadId: "p_ada",
      lastPublishedAt: iso(-2),
      clientActions: [
        { id: "ca_2", title: "Send us the team photos", dueOn: iso(6), createdAt: iso(-3) },
        { id: "ca_3", title: "Confirm the pricing copy", dueOn: iso(9), createdAt: iso(-1) },
      ],
      tasks: [
        {
          id: "t_4",
          projectId: "prj_site",
          title: "Rework pricing section",
          responsibleId: "p_ada",
          status: "in_progress",
          dueOn: iso(2),
          deliverableId: "dlv_pages",
          stateChangedAt: iso(-1),
          blockers: [],
        },
        {
          id: "t_5",
          projectId: "prj_site",
          title: "Build About page",
          responsibleId: "p_femi",
          status: "blocked",
          dueOn: iso(5),
          deliverableId: null,
          stateChangedAt: iso(-3),
          blockers: [
            {
              id: "b_3",
              kind: "client",
              clientActionId: "ca_2",
              note: "No team photos yet",
              createdAt: iso(-3),
              resolvedAt: null,
            },
          ],
        },
        {
          id: "t_6",
          projectId: "prj_site",
          title: "Set up staging deploy",
          responsibleId: "p_femi",
          status: "done",
          dueOn: iso(-4),
          deliverableId: null,
          stateChangedAt: iso(-4),
          blockers: [],
        },
        {
          id: "t_7",
          projectId: "prj_site",
          title: "Cross-browser pass",
          responsibleId: "p_chike",
          status: "todo",
          dueOn: iso(11),
          deliverableId: null,
          stateChangedAt: iso(-1),
          blockers: [],
        },
      ],
      deliverables: [
        {
          id: "dlv_pages",
          name: "Page designs",
          typeName: "Page designs",
          status: "changes_requested",
          ownerId: "p_ada",
          round: 2,
          roundsIncluded: 2,
          stateChangedAt: iso(-2),
          reviewUrl: "https://www.figma.com/file/ovis-pages",
          linkAccessOk: true,
          checklist: null,
        },
      ],
    },
  ],
};
